version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

dependencies:
  pre:
    - cat Gemfile.lock | grep -A 1 "BUNDLED WITH"
      BUNDLED WITH
      2.1.4
    - gem install bundler -v '2.1.4'

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v
      - ruby/bundle-install