---
development:
  cloud_name: dvfogjpzz
  api_key: '154433638341233'
  api_secret: E_c12oq-WrjUMw1LBMh1GsgqguY
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dvfogjpzz
  api_key: '154433638341233'
  api_secret: E_c12oq-WrjUMw1LBMh1GsgqguY
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dvfogjpzz
  api_key: '154433638341233'
  api_secret: E_c12oq-WrjUMw1LBMh1GsgqguY
  enhance_image_tag: true
  static_file_support: false
